Define own resize in NCPad and fix param type of SetLabel()
Explicitly override resize() to avoid conflicts from NCursesWindow
definition since there is another resize definition as well

Fixes
src/NCPad.h:164:18: error: 'NCPad::resize' hides overloaded virtual function [-Werror,-Woverloaded-virtual]

NCTablePad.h:132:18: error: 'NCTableTag::SetLabel' hides overloaded virtual function [-Werror,-Woverloaded-virtual]

Signed-off-by: Khem Raj <raj.khem@gmail.com>